### ISSUE TITLE
Moving this repository to rpm-py-installer group

### ISSUE THREAD

**Issue by junaruga** [rpm-py-installer/rpm-py-installer#277]
I am considering moving this repository `junaruga/rpm-py-installer` to the `rpm-py-installer/rpm-py-installer` by creating The `rpm-py-installer` group. I hope this project thirties beyond me and without my activities.

If you want a feature, you can send PR, and you can find a path to be the maintainer. I think we can add/remove the maintainer for each function, such as Mac OS support, the latest RPM support, etc.

Any thoughts?

**Comment by nforro** [comment]
Makes sense, however I'm not sure about the future of this project. In [`specfile`](https://github.com/packit/specfile) (`rebase-helper`, `packit`) we switched to [`rpm-shim`](https://github.com/packit/rpm-shim), which is not really a replacement (it only imports installed system RPM bindings if possible), but it is sufficient for our purposes.

**Comment by junaruga** [comment]
All right. The `rpm-shm` looks nice, and can be alternative. I believe that importing installed system RPM bindings satisfies the most of the people's cases. Does it only work in Linux?

I think we can do 2 steps. I will work on it.

* Move this repository to rpm-py-installer group
* Add a text to consider using `rpm-shm` in README.

**Comment by junaruga** [comment]
> That's a good question. There are [hardcoded](https://github.com/packit/rpm-shim/blob/27b932cce30f4d37a7d9f1410b6685ff4a8cc291/rpm/__init__.py#L46) system Python interpreters, but that could be adjusted. I haven't tested it on any other platform than Linux though.

I see. Thanks for the explanation.

**Comment by nforro** [comment]
> @nforro Do you mind that you create the `rpm-py-installer` public group, and migrate this repository to it? I needed to register my personal email and github account to the group. I don't want to do it.

I've created the [organization](https://github.com/rpm-py-installer) but I don't have permissions to migrate the repository.

**Comment by junaruga** [comment]
> I've created the [organization](https://github.com/rpm-py-installer) but I don't have permissions to migrate the repository.

Thanks! I try to migrate the repository.

**Comment by junaruga** [comment]
> Thanks! I try to migrate the repository.

Migrated!
https://github.com/rpm-py-installer/rpm-py-installer

It seems the old repository URL below is redirected to the new URL.
https://github.com/junaruga/rpm-py-installer

**Comment by junaruga** [comment]
@nforro Do you mind updating necessary documents from the file list below? You can also add or update with your name and email in the `setup.py`.

```
$ pwd
/home/jaruga/git/rpm-py-installer

$ grep -r junaruga *
ci/rpm-py-installer-docker/build.sh:    docker.io/junaruga/rpm-py-installer-docker:26
ci/rpm-py-installer-docker/build.sh:docker push docker.io/junaruga/rpm-py-installer-docker:26
ci/rpm-py-installer-docker/README.md:See: https://hub.docker.com/r/junaruga/rpm-py-installer-docker/
docs/users_guide.md:$ [VAR=VALUE] /path/to/python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
docs/users_guide.md:  $ RPM_PY_VERBOSE=true python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
docs/users_guide.md:- A4. The version mapping's default behavior is to use same version as the system RPM's version. See [#94](https://github.com/junaruga/rpm-py-installer/issues/94) for details.
docs/users_guide.md:  $ RPM_PY_VERSION=4.13.0 python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
docs/users_guide.md:  or set `setup.py`'s `install_requires` conditionally. Refer to the sample [`setup.py`](/tests/sample/setup.py) or [rebase-helper's `setup.py`](https://github.com/rebase-helper/rebase-helper/blob/master/setup.py). If you have a request for this situation, ask us on [the issue page](https://github.com/junaruga/rpm-py-installer/issues/134).
README.md:[![GitHub Actions Build Status](https://github.com/junaruga/rpm-py-installer/actions/workflows/build-and-test.yml/badge.svg)](https://github.com/junaruga/rpm-py-installer/actions/workflows/build-and-test.yml)
README.md:$ python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
README.md:* Mac OSX (ticket [#155](https://github.com/junaruga/rpm-py-installer/issues/155))
setup.py:    url='https://github.com/junaruga/rpm-py-installer',
tests/conftest.py:        'https://raw.githubusercontent.com/junaruga/rpm-py-installer'
```

**Comment by nforro** [comment]
https://github.com/rpm-py-installer/rpm-py-installer/pull/278

**Comment by nforro** [comment]
There is still `docker.io/junaruga/rpm-py-installer-docker`, maybe you want to migrate that as well.

**Comment by junaruga** [comment]
Good catch! I suppose the docker.io link (`https://hub.docker.com/repository/docker/junaruga/rpm-py-installer-docker/general`) is not used now. It's not referred from any files. 

```
$ grep -r rpm-py-installer-docker .github/ .
grep: ./.git/index: binary file matches
./ci/rpm-py-installer-docker/build.sh:docker build -t rpm-py-installer-docker .
./ci/rpm-py-installer-docker/build.sh:docker tag rpm-py-installer-docker \
./ci/rpm-py-installer-docker/build.sh:    docker.io/junaruga/rpm-py-installer-docker:26
./ci/rpm-py-installer-docker/build.sh:docker push docker.io/junaruga/rpm-py-installer-docker:26
./ci/rpm-py-installer-docker/README.md:See: https://hub.docker.com/r/junaruga/rpm-py-installer-docker/
```

I think you can remove it.

```
$ git rm -r ci/rpm-py-installer-docker/
```

**Comment by junaruga** [comment]
> I suppose the docker.io link (https://hub.docker.com/repository/docker/junaruga/rpm-py-installer-docker/general) is not used now.

I deleted the DockerHub repository now. The last update was 6 years ago.
